2025-05-14 03:08:00 | INFO     | __main__:__init__:34 - Bot initialized
2025-05-14 03:08:03 | INFO     | services.firebase_service:initialize:30 - Firebase connection established
2025-05-14 03:08:03 | INFO     | services.firebase_service:__init__:22 - Firebase service initialized
2025-05-14 03:08:03 | INFO     | cogs.dsm:__init__:462 - DSM cog initialized
2025-05-14 03:08:03 | INFO     | __main__:setup_hook:42 - Cogs loaded
2025-05-14 03:08:06 | INFO     | cogs.dsm:before_daily_standup:1024 - Daily standup task started
2025-05-14 03:08:06 | INFO     | __main__:on_ready:46 - Logged in as E-Konsulta Internals
2025-05-14 03:08:07 | INFO     | services.firebase_service:load_tasks:123 - Loaded tasks from Firebase
2025-05-14 03:08:07 | INFO     | cogs.dsm:on_ready:2276 - Tasks loaded from Firebase
2025-05-14 03:08:07 | INFO     | cogs.dsm:on_ready:2283 - Loaded DSM messages for guild 998850525174972486
2025-05-14 03:08:07 | INFO     | cogs.dsm:on_ready:2283 - Loaded DSM messages for guild 1365369294623608882
2025-05-14 03:08:07 | INFO     | cogs.dsm:on_ready:2292 - DSM messages loaded from config
2025-05-14 03:08:19 | INFO     | cogs.dsm:simulate_dsm:2303 - Manual DSM triggered by pataponz in stimmie's server
2025-05-14 03:08:20 | ERROR    | cogs.dsm:simulate_dsm:2324 - Error handling previous thread: 400 Bad Request (error code: 50035): Invalid Form Body
In channel_id: Value "{'created_at': '2025-05-14T02:38:49.063145', 'date': '2025-05-14', 'thread_id': '1371919634269344005'}" is not snowflake.
2025-05-14 03:08:21 | ERROR    | cogs.dsm:simulate_dsm:2373 - Error in simulate_dsm: module 'datetime' has no attribute 'now'
2025-05-14 03:08:39 | INFO     | cogs.dsm:simulate_dsm:2303 - Manual DSM triggered by pataponz in stimmie's server
2025-05-14 03:08:40 | ERROR    | cogs.dsm:simulate_dsm:2324 - Error handling previous thread: 400 Bad Request (error code: 50035): Invalid Form Body
In channel_id: Value "{'created_at': '2025-05-14T02:38:49.063145', 'date': '2025-05-14', 'thread_id': '1371919634269344005'}" is not snowflake.
2025-05-14 03:08:40 | ERROR    | cogs.dsm:simulate_dsm:2373 - Error in simulate_dsm: module 'datetime' has no attribute 'now'
2025-05-14 03:10:57 | INFO     | cogs.dsm:cog_unload:492 - DSM cog unloaded
